[build]
	environment = { GENERATE_SOURCEMAP = "false" }
	base = "long-war-builder/"
	publish = "build/"
	command = "craco build"

[[redirects]]
	from = "/*"
	to = "/index.html"       
	status = 200

[[plugins]]
	package = "netlify-plugin-image-optim"

[[plugins]]
	package = "netlify-plugin-hashfiles"
